#!/usr/bin/expect -f
##############################################################################
##############################################################################
# Author: Bob Brandt projects@brandt.ie,                                     #
#                                                                            #
# AlcatelSFTP host username password file                                    #
#                                                                            #
#  The purpose of this script it to save to configuration of the Alcatel     #
# switches in the network.  This is needed because not every VLAN/Port       #
# change is saved and if the switch/stack were to reboot you may loss your   #
# configuration changes.                                                     #
#                                                                            #
# Comments can be used but must be preceeded by a hash symbol (#)            #
# All Comments are to be preceded by a hash symbol (#) (Maximum of 78 chars) #
#                                                                            #
##############################################################################
##############################################################################

set host [lrange $argv 0 0]
set user [lrange $argv 1 1]
set pass [lrange $argv 2 2]
set file [lrange $argv 3 3]

#log_file /opt/opw/saveswitch/$prompt.log
log_user 0
set timeout 120
spawn sftp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $user@$host:$file

# Login
expect {
	"*?assword" { 
		sleep 1
		send "$pass\n" 
	}
	"(yes/no)? " { 
		send "yes\n"
		expect {
			"*?assword" { 
				sleep 1
				send "$pass\n" 
			}
	        }
	}
	default {
	        send_error "$prompt ($host) Login failed\n"
	        send_log "$prompt ($host) Login failed\n"
	        exit 1
	}
}
expect eof
exit 0


