#!/bin/bash
#
#     Script to create Disk Usage Report
#     Bob Brandt <projects@brandt.ie>
#  
VERSION=0.1

mailserver=smtp.opw.ie
from=diskusage@opw.ie
to=storagealerts@opw.ie

usage() {
    [ "$2" == "" ] || echo -e "$2"
    echo -e "Usage: $0 [options]"
    echo -e "Options:"
    echo -e " -h, --help     display this help and exit"
    echo -e " -v, --version  output version information and exit"
    exit ${1:-0}
}

version() {
    echo -e "$0 $VERSION"
    echo -e "Copyright (C) 2011 Free Software Foundation, Inc."
    echo -e "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>."
    echo -e "This is free software: you are free to change and redistribute it."
    echo -e "There is NO WARRANTY, to the extent permitted by law.\n"
    echo -e "Written by Bob Brandt <projects@brandt.ie>."
    exit 0
}

convertSizeHuman(){
    declare -i size="$1"
    formatstr="${2:-%0.2f}"

    if (( $size >= 1073741824 )); then
        printf "$formatstr TB" $( echo "scale=2; $size/1073741824" | bc )
    elif (( $size >= 1048576 )); then
        printf "$formatstr GB"  $( echo "scale=2; $size/1048576" | bc )
    elif (( $size >= 1024 )); then
        printf "$formatstr MB"  $( echo "scale=2; $size/1024" | bc )
    elif (( $size >= 0 )); then
        printf "$formatstr KB" $size
    else
        return 1
    fi
}

generateReport() {
    csvfile="$1"
    title="$2"
    tmp=$( grep ',"1",' $csvfile )

    declare -i total=$( echo "$tmp" | grep ',"./"' | head -n 1 | sed 's|^"\([0-9]*\)",.*|\1|' )
    
    tmp=$( echo "$tmp" | grep -v ',"./"' )
    declare -i count=$( echo "$tmp" | wc -l )
    declare -i average=$( echo "$tmp" | sed 's|^"\([0-9]*\)",.*|\1|' | paste -sd+ | bc )
    declare -i average=$(( $average/$count ))

    echo -e "\nBelow is the Disk Usage Report for $title ($( date +%Y/%m/%d )).\n"

    echo "              Total Size: "$( convertSizeHuman $total "%7.2f")
    echo "Average Root Folder Size: "$( convertSizeHuman $average "%7.2f")" ($count root folders)"

    echo -e "\nThe following are the worst offenders:"


    IFS=$'\n'
    for line in $( echo "$tmp" | sed 's|^"\([0-9]*\)",.*|\1,&|' | sort -nr ); do
        declare -i size=$( echo "$line" | cut -d "," -f 1 )
        if (( $size >= $average )); then
            path=$( echo "$line" | cut -d "," -f 5 | sed 's|"||g')
            echo -e $( convertSizeHuman $size "%8.2f")"\t$path"
        fi
    done
}

# Execute getopt
ARGS=$(getopt -o vh -l "help,version" -n "$0" -- "$@") || usage 1 " "

#Bad arguments
#[ $? -ne 0 ] && usage 1 "$0: No arguments supplied!\n"

eval set -- "$ARGS";

while /bin/true ; do
    case "$1" in
    -h | --help )         usage 0 ;;
    -v | --version )      version ;;
    -- )                  shift ; break ;;
    * )                   usage 1 "$0: Invalid argument!\n" ;;
    esac
    shift
done

generateReport "/home/BrandtB/dublinusers.du.csv" "DublinUsers"
# generateReport "/home/BrandtB/dublingroups.du.csv" "DublinGroups"

exit $?
