#!/bin/bash

mailserver=smtp.opw.ie
from=groupusage@opw.ie
to=storagealerts@opw.ie

mount -a
set smtp=$mailserver
/opt/opw/DiskUsage/DiskUsage /mnt/opw-filer01/dublingroups/* | mailx -s "Dublin Group Usage Report" -r "$from" "$to" &
/opt/opw/DiskUsage/DiskUsage /mnt/opw-filer02/dublinusers/* | mailx -s "Dublin Users Usage Report" -r "$from" "$to" &
/opt/opw/DiskUsage/DiskUsage /mnt/opw-filer03/trimgroups/* | mailx -s "Trim Group Usage Report" -r "$from" "$to" &
/opt/opw/DiskUsage/DiskUsage /mnt/opw-filer04/trimusers/* | mailx -s "Trim Users Usage Report" -r "$from" "$to" &

